### ISSUE TITLE
Fix image model

### ISSUE THREAD

**Issue by nda-silva** [PacSmack/ArtInerary#16]
- Image model cannot be seeded because the attributes being passed onto it do not match
- Route /get all can't work because user is not associated to the image model
- Create associations based on our tables
- What is our reference table for(?)

**Comment by LindseyKrause** [comment]
Reference table is for the Reference photos - We may not need this if we just hardcode the images into the site directly, but for future functionality, we may want the person with the most likes to be able to choose and upload a reference photo ? 

I'm distinguishing between reference photos and images because the images are what the user would upload and the reference photos would appear differently on the page.

**Comment by LindseyKrause** [comment]
` catchphrase: {
            type: DataTypes.STRING,
            allowNull: true
        },`

I added that to include the user 's catchphrase to the profile.  I didn't add the profile photo yet because I don't think that needs to be part of the MVP.  Let me know if you think differently.  I just want to make sure we can get one image uploaded.

**Comment by nda-silva** [comment]
![image](https://user-images.githubusercontent.com/79550591/122636704-77031400-d09f-11eb-87c6-84e0f00a043e.png)

the association's table is not working still, it shouldn't throw an error when running npm start, if you need help fixing it just let me know and I'll take a look tomorrow

When you pulled it to the develop branch, was it working?

**Comment by LindseyKrause** [comment]
I'm going to pull the develop branch and then merge into modals so I can look at the whole code base.  I'll see what I can figure out with the cyclic dependency.  If you think you know how to fix it though, please do and let me know.

**Comment by LindseyKrause** [comment]
This should be fixed, making pull request.
